[CI/CD] Deploy to staging or development environments

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -4,29 +4,40 @@ on:
   push:
     branches:
       - develop
-      - deploy
+      - staging
 
 jobs:
   deploy:
     runs-on: ubuntu-latest
     steps:
-       - name: Deploy Dash app
-         uses: appleboy/ssh-action@v1.0.3
-         with:
-           host: ${{secrets.SSH_HOST}} # IP address of the server
-           key: ${{secrets.SSH_KEY}} # Private or public key of the server
-           username: ${{ secrets.SSH_USERNAME }} # User of the server
-           port: ${{ secrets.SSH_PORT }}
-           script: |
-             if ! [ -d "$HOME/ecoacoustics-dashboard/" ]; then
-               echo 'repo does not exist!'
-               exit 1
-             fi
-             cd $HOME/ecoacoustics-dashboard/
-             ./deploy-app.sh
-             if [ $? != 0 ]; then
-               echo "deploy-app.sh failed, check the server logs!"
-               exit 1
-             fi
-             echo 'Deployment to echodash.co.uk succesful!'
-
+      - name: Set environment variables for staging
+        if: endsWith(github.ref, '/staging')
+        run: |
+          echo "BRANCH=staging" >> $GITHUB_ENV
+      - name: Set environment variables for development
+        if: endsWith(github.ref, '/develop')
+        run: |
+          echo "BRANCH=develop" >> $GITHUB_ENV
+      - name: Deploy Dash app
+        uses: appleboy/ssh-action@v1.0.3
+        with:
+          host: ${{secrets.SSH_HOST}} # IP address of the server
+          key: ${{secrets.SSH_KEY}} # Private or public key of the server
+          username: ${{ secrets.SSH_USERNAME }} # User of the server
+          port: ${{ secrets.SSH_PORT }}
+          script: |
+            echo 'Deploying from ${{ env.BRANCH }} on echodash.co.uk...'
+            if ! [ -d "$HOME/ecoacoustics-dashboard/" ]; then
+              echo 'repo does not exist!'
+              exit 1
+            fi
+            cd $HOME/ecoacoustics-dashboard/
+            git checkout ${{ env.BRANCH }}
+            git pull
+            git reset --hard origin/${{ env.BRANCH }}
+            $HOME/ecoacoustics-dashboard/deploy-${{ env.BRANCH }}.sh
+            if [ $? != 0 ]; then
+              echo "deploy-${{ env.BRANCH }}.sh failed, check the server logs!"
+              exit 1
+            fi
+            echo 'Deployment to echodash.co.uk succesful!'
